# Generated by Django 3.0.6 on 2020-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='project',
            name='programming_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='(Elevator Pitch)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is currently active?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='the date and time this project was posted'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
